mqtt:
 client:
  protocol: 4
 connection:
  host: 192.168.1.3
  port: 1883
  keepalive: 60
 private_path: robot
    
       
bridge:
#Twist data Communication
-factory: mqtt_bridge.bridge:RosToMqttBridge
 msg_type: geometry_msgs.msg:Twist
 topic_from: /cmd_vel
 topic_to: ~/cmd_vel 
-factory: mqtt_bridge.bridge:MqttToRosBridge
 msg_type: geometry_msgs.msg:Twist
 topic_from: ~/cmd_vel 
 topic_to: /cmd_vel
#Float data Communication
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: std_msgs.msg:Float32
  topic_from: /voltage
  topic_to: ~/voltageToMqtt
#Bool Data Communication
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: std_msgs.msg:Bool
  topic_from: /robot/boolToMqtt
  topic_to: ~/boolToMqtt
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: std_msgs.msg:Bool
  topic_from: ~/boolToRos
  topic_to: /robot/boolToRos
#Signed Int List Communication Using Custom msg Type
- factory: mqtt_bridge.bridge:RosToMqttBridge
  msg_type: mqtt_bridge.msg:IntList 
  topic_from: /robot/intListToMqtt
  topic_to: ~/intListToMqtt
- factory: mqtt_bridge.bridge:MqttToRosBridge
  msg_type: mqtt_bridge.msg:IntList
  topic_from: ~/intListToRos
  topic_to: /robot/intListToRos
